dataset:
  name: "MovieLens1M"
  path: "./data/MovieLens1M"
  val_ratio: 0.1
  test_ratio: 0.1
  negative_sampling_ratio: 1.0
  min_rating: 4

training:
  epochs: 20
  learning_rate: 0.005
  device: "cuda"

models:
  embedding_dim: 64
  lightgcn:
    num_layers: 3
  gat:
    num_layers: 2
  graphsage:
    num_layers: 2
